package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.ApprovalPO;

public interface ApprovalPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval
     *
     * @mbggenerated Thu Feb 06 18:04:30 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval
     *
     * @mbggenerated Thu Feb 06 18:04:30 CST 2025
     */
    int insert(ApprovalPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval
     *
     * @mbggenerated Thu Feb 06 18:04:30 CST 2025
     */
    int insertSelective(ApprovalPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval
     *
     * @mbggenerated Thu Feb 06 18:04:30 CST 2025
     */
    ApprovalPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval
     *
     * @mbggenerated Thu Feb 06 18:04:30 CST 2025
     */
    int updateByPrimaryKeySelective(ApprovalPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval
     *
     * @mbggenerated Thu Feb 06 18:04:30 CST 2025
     */
    int updateByPrimaryKey(ApprovalPO record);
}