package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.DeployHistoryPO;

public interface DeployHistoryPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_history
     *
     * @mbggenerated Thu Aug 15 21:28:25 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_history
     *
     * @mbggenerated Thu Aug 15 21:28:25 CST 2024
     */
    int insert(DeployHistoryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_history
     *
     * @mbggenerated Thu Aug 15 21:28:25 CST 2024
     */
    int insertSelective(DeployHistoryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_history
     *
     * @mbggenerated Thu Aug 15 21:28:25 CST 2024
     */
    DeployHistoryPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_history
     *
     * @mbggenerated Thu Aug 15 21:28:25 CST 2024
     */
    int updateByPrimaryKeySelective(DeployHistoryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_history
     *
     * @mbggenerated Thu Aug 15 21:28:25 CST 2024
     */
    int updateByPrimaryKey(DeployHistoryPO record);
}