package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.GroupHostPO;

public interface GroupHostPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_host
     *
     * @mbggenerated Thu Nov 09 22:31:54 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_host
     *
     * @mbggenerated Thu Nov 09 22:31:54 CST 2023
     */
    int insert(GroupHostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_host
     *
     * @mbggenerated Thu Nov 09 22:31:54 CST 2023
     */
    int insertSelective(GroupHostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_host
     *
     * @mbggenerated Thu Nov 09 22:31:54 CST 2023
     */
    GroupHostPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_host
     *
     * @mbggenerated Thu Nov 09 22:31:54 CST 2023
     */
    int updateByPrimaryKeySelective(GroupHostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_host
     *
     * @mbggenerated Thu Nov 09 22:31:54 CST 2023
     */
    int updateByPrimaryKey(GroupHostPO record);
}