package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.HostMonitorPO;

public interface HostMonitorPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int insert(HostMonitorPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int insertSelective(HostMonitorPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    HostMonitorPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int updateByPrimaryKeySelective(HostMonitorPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int updateByPrimaryKey(HostMonitorPO record);
}