package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.HostTerminalLogPO;

public interface HostTerminalLogPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_terminal_log
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_terminal_log
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int insert(HostTerminalLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_terminal_log
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int insertSelective(HostTerminalLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_terminal_log
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    HostTerminalLogPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_terminal_log
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int updateByPrimaryKeySelective(HostTerminalLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_terminal_log
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int updateByPrimaryKey(HostTerminalLogPO record);
}