package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.HostPO;

public interface HostPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host
     *
     * @mbggenerated Thu Nov 23 08:24:53 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host
     *
     * @mbggenerated Thu Nov 23 08:24:53 CST 2023
     */
    int insert(HostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host
     *
     * @mbggenerated Thu Nov 23 08:24:53 CST 2023
     */
    int insertSelective(HostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host
     *
     * @mbggenerated Thu Nov 23 08:24:53 CST 2023
     */
    HostPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host
     *
     * @mbggenerated Thu Nov 23 08:24:53 CST 2023
     */
    int updateByPrimaryKeySelective(HostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host
     *
     * @mbggenerated Thu Nov 23 08:24:53 CST 2023
     */
    int updateByPrimaryKey(HostPO record);
}