package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.ServerLoadMonitorPO;

public interface ServerLoadMonitorPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_load_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_load_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int insert(ServerLoadMonitorPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_load_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int insertSelective(ServerLoadMonitorPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_load_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    ServerLoadMonitorPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_load_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int updateByPrimaryKeySelective(ServerLoadMonitorPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_load_monitor
     *
     * @mbggenerated Mon Apr 14 17:59:37 CST 2025
     */
    int updateByPrimaryKey(ServerLoadMonitorPO record);
}