package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.ServerAccountPO;

public interface ServerAccountPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_account
     *
     * @mbggenerated Fri Jan 26 21:17:24 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_account
     *
     * @mbggenerated Fri Jan 26 21:17:24 CST 2024
     */
    int insert(ServerAccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_account
     *
     * @mbggenerated Fri Jan 26 21:17:24 CST 2024
     */
    int insertSelective(ServerAccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_account
     *
     * @mbggenerated Fri Jan 26 21:17:24 CST 2024
     */
    ServerAccountPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_account
     *
     * @mbggenerated Fri Jan 26 21:17:24 CST 2024
     */
    int updateByPrimaryKeySelective(ServerAccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server_account
     *
     * @mbggenerated Fri Jan 26 21:17:24 CST 2024
     */
    int updateByPrimaryKey(ServerAccountPO record);
}