package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.TerminalSessionInstanceCommandPO;
import com.rany.cake.devops.base.infra.po.TerminalSessionInstanceCommandPOWithBLOBs;

public interface TerminalSessionInstanceCommandPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance_command
     *
     * @mbggenerated Mon Dec 18 20:57:06 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance_command
     *
     * @mbggenerated Mon Dec 18 20:57:06 CST 2023
     */
    int insert(TerminalSessionInstanceCommandPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance_command
     *
     * @mbggenerated Mon Dec 18 20:57:06 CST 2023
     */
    int insertSelective(TerminalSessionInstanceCommandPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance_command
     *
     * @mbggenerated Mon Dec 18 20:57:06 CST 2023
     */
    TerminalSessionInstanceCommandPOWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance_command
     *
     * @mbggenerated Mon Dec 18 20:57:06 CST 2023
     */
    int updateByPrimaryKeySelective(TerminalSessionInstanceCommandPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance_command
     *
     * @mbggenerated Mon Dec 18 20:57:06 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(TerminalSessionInstanceCommandPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance_command
     *
     * @mbggenerated Mon Dec 18 20:57:06 CST 2023
     */
    int updateByPrimaryKey(TerminalSessionInstanceCommandPO record);
}