package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.TerminalSessionInstancePO;

public interface TerminalSessionInstancePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance
     *
     * @mbggenerated Sun Dec 17 16:01:56 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance
     *
     * @mbggenerated Sun Dec 17 16:01:56 CST 2023
     */
    int insert(TerminalSessionInstancePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance
     *
     * @mbggenerated Sun Dec 17 16:01:56 CST 2023
     */
    int insertSelective(TerminalSessionInstancePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance
     *
     * @mbggenerated Sun Dec 17 16:01:56 CST 2023
     */
    TerminalSessionInstancePO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance
     *
     * @mbggenerated Sun Dec 17 16:01:56 CST 2023
     */
    int updateByPrimaryKeySelective(TerminalSessionInstancePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_session_instance
     *
     * @mbggenerated Sun Dec 17 16:01:56 CST 2023
     */
    int updateByPrimaryKey(TerminalSessionInstancePO record);
}