package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.UserEventLogPO;

public interface UserEventLogPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event_log
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event_log
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    int insert(UserEventLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event_log
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    int insertSelective(UserEventLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event_log
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    UserEventLogPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event_log
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    int updateByPrimaryKeySelective(UserEventLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event_log
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    int updateByPrimaryKey(UserEventLogPO record);
}