package com.rany.cake.devops.base.infra.mapper;

import com.rany.cake.devops.base.infra.po.WebhookConfigPO;

public interface WebhookConfigPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_config
     *
     * @mbggenerated Sun Nov 03 10:48:26 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_config
     *
     * @mbggenerated Sun Nov 03 10:48:26 CST 2024
     */
    int insert(WebhookConfigPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_config
     *
     * @mbggenerated Sun Nov 03 10:48:26 CST 2024
     */
    int insertSelective(WebhookConfigPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_config
     *
     * @mbggenerated Sun Nov 03 10:48:26 CST 2024
     */
    WebhookConfigPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_config
     *
     * @mbggenerated Sun Nov 03 10:48:26 CST 2024
     */
    int updateByPrimaryKeySelective(WebhookConfigPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webhook_config
     *
     * @mbggenerated Sun Nov 03 10:48:26 CST 2024
     */
    int updateByPrimaryKey(WebhookConfigPO record);
}