# 使用 openjdk:8 作为基础镜像
FROM openjdk:8

# 定义构建参数和环境变量
ARG ENV=prod
ENV APP_NAME=cake-devops-base
ENV APP_HOME=/home/admin/$APP_NAME

# 创建目录
RUN mkdir -p $APP_HOME/logs

# 添加 appctl.sh 脚本
ADD /APP-META/appctl.sh /home/admin/appctl.sh
RUN chmod +x /home/admin/appctl.sh

# 挂载目录
VOLUME /tmp

# 添加 JAR 文件
ADD start/target/cake-devops-service.jar /home/admin/cake-devops-base/cake-devops-service.jar

# 设置 ENTRYPOINT
ENTRYPOINT ["/home/admin/appctl.sh"]
CMD ["cake-devops-base", "start", "prod"]
