server:
  port: 8300

dubbo:
  application:
    id: cake-ops-service
    name: cake-ops-service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  scan:
    basePackages: com.rany.cake.devops

spring:
  profiles:
    active: dev
  redis:
    url: redis://127.0.0.1:6379
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cake_devops?allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: Zsw131400.
      # 初始化连接大小
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      # 最大连接数
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,log4j2,config
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;

  application:
    name: cake-devops-base
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    connection-timeout: 5000
    virtual-host: /

enable:
  sql:
    print:
      log: true
warn:
  sql:
    time: 300

mybatis:
  mapper-locations: classpath:com/rany/cake/devops/base/infra/mapper/*.xml, classpath:com/rany/cake/devops/base/infra/dao/*.xml
  type-aliases-package: com.rany.cake.devops.base.infra, com.rany.cake.devops.base.domain



devops:
  redisson:
    address: 127.0.0.1:6379
    type: STANDALONE
    enabled: true
  log:
    queueName: devops-log-queue
    exchangeName: devops-log-exchange
    bindingKey: devops-log-key
  app:
    tenantId: 768821467507994624
  package:
    balancer: random
  cr:
    channel: harbor # 支持harbor或者阿里云acr
    harbor:
      harborUrl:
      harborUser:
      harborPassword:
    aliyun:
      instanceId:
      region:
      accessKey:
      secretKey:


