server:
  port: 8300
  tomcat:
    connection-timeout: 18000000

logging:
  file:
    path: /home/admin/cake-devops-base/logs

cms:
  env: test
  oss:
    endpoint: https://rany-ops.oss-cn-hangzhou.aliyuncs.com
  page:
    #    version: 1.0.22
    path: cake-devops-base/${cms.page.version}/index.html
  site:
    name: cake-devops-base


dubbo:
  application:
    id: cake-devops-service
    name: cake-devops-service
  protocol:
    name: dubbo
    port: -1
  scan:
    basePackages: com.rany.cake.devops

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cake_devops?allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: Zsw131400.
      # 初始化连接大小
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      # 最大连接数
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #      filters: stat,log4j2,config
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;

  application:
    name: cake-devops-service
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    connection-timeout: 5000
    virtual-host: /

rany:
  ops:
    message:
      sms:
        fakeAccount: 1528683621@qq.com
        fakeIdd: "+86"


cake:
  mybatis:
    tenant-limit: false
    enable-print: true

mybatis:
  mapper-locations: classpath:com/rany/cake/devops/base/infra/mapper/*.xml, classpath:com/rany/cake/devops/base/infra/dao/*.xml
  type-aliases-package: com.rany.cake.devops.base.infra, com.rany.cake.devops.base.domain

devops:
  biz-config:
    departments:
      - label: Honda汽车
        value: cake-honda
        abbr: HONDA
      - label: QA质量团队
        value: cake-qa
        abbr: QA
      - label: 数据团队
        value: cake-data
        abbr: DATA
      - label: 运维团队
        value: cake-ops
        abbr: OPS
      - label: 职能团队
        value: cake-hr
        abbr: HR
  sls:
    project: cake-devops-log
    logstore: deploy-log
    endpoint: https://cn-hangzhou.log.aliyuncs.com
    accessKeyId: xxxx
    accessKeySecret: xxxx
  log:
    queueName: devops-log-queue
    exchangeName: devops-log-exchange
    bindingKey: devops-log-key
  app:
    tenantId: 768460649511661568
  cr:
    channel: aliyun # 支持harbor或者阿里云acr
    sonar:
      url: http://localhost:9000
      token: sqa_3da04fbfb55e03b741592681d888d991bedeb36a
    harbor:
      harborUrl:
      harborUser:
      harborPassword:
      default-project-id:
    aliyun:
      instanceId:
      region: cn-hangzhou
      accessKey:
      secretKey:
      namespace: cake-devops-base
      host: registry.cn-hangzhou.aliyuncs.com
      username: 1528683621@qq.com
      password: Zsw131400

easy:
  sso:
    client:
      enable: true
      client-type: web
      sso-server: http://127.0.0.1:8765/
      login-url: http://127.0.0.1:8765/sso/loginPage
      logout-url: /sso/logout
      ignore-urls: /ok,/sso/loginPage,/sso/login,/oauth/login,/cake/expose-api/**,/api/keep-alive/**, /api/ws/**,/api/config/**
      ignore-resources: .js, .css, .jpg, .png, .ico, .html
      ajax-failure-response:
        content-type: application/json
        code: 401
        msg: 用户未登录
    redis:
      address: redis://127.0.0.1:6379

expose:
  api:
    access:
      header: accessToken
      secret: agent_access

machine:
  monitor:
    latest:
      version: 0.0.1-SNAPSHOT
    default:
      url: "http://{}:9220"
      access:
        header: accessToken
        token: agent_access