cms:
  env: test
  page:
    version: 1.0.22

dubbo:
  config-center:
    address: zookeeper://zookeeper.default.svc.cluster.local:2181
  registry:
    address: zookeeper://zookeeper.default.svc.cluster.local:2181
    timeout: 30000
  metadata-report:
    address: zookeeper://zookeeper.default.svc.cluster.local:2181
    timeout: 30000

spring:
  redis:
    url: redis://redis.default.svc.cluster.local:6379
  datasource:
    druid:
      url: jdbc:mysql://rm-bp1xar5yv7845gc8hco.mysql.rds.aliyuncs.com:3306/cake_devops?allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username:
      password:
  rabbitmq:
    addresses: rabbitmq.default.svc.cluster.local:5672
    username: guest
    password: guest
    connection-timeout: 5000
    virtual-host: /

devops:
  redisson:
    address: redis.default.svc.cluster.local:6379
    type: STANDALONE
    enabled: true

easy:
  sso:
    client:
      sso-server: http://test.sso.rany.com/
      login-url: http://test.sso.rany.com/sso/loginPage
      sso-callback-url: http://test.sso.rany.com/sso/code
    redis:
      address: redis://redis.default.svc.cluster.local:6379
