server:
  port: 8300
  tomcat:
    connection-timeout: 18000000
logging:
  file:
    path: /Users/yuanjinxiu/cake-devops-base/logs

cms:
  env: test
  oss:
    endpoint: https://rany-ops.oss-cn-hangzhou.aliyuncs.com
  page:
    version: 1.0.17
    path: cake-devops-base/${cms.page.version}/index.html
  site:
    name: cake-devops-base

dubbo:
  config-center:
    address: zookeeper://127.0.0.1:2181
  registry:
    address: zookeeper://127.0.0.1:2181
    client: curator
  metadata-report:
    address: zookeeper://127.0.0.1:2181

spring:
  redis:
    url: redis://127.0.0.1:6379
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/cake_devops?allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    connection-timeout: 5000
    virtual-host: /


devops:
  redisson:
    address: 127.0.0.1:6379
    type: STANDALONE
    enabled: true



easy:
  sso:
    client:
      enable: true
      client-type: web
      sso-server: http://127.0.0.1:8765/
      login-url: http://127.0.0.1:8765/sso/loginPage
      logout-url: /sso/logout
      ignore-urls: /ok,/sso/loginPage,/sso/login,/oauth/login,/cake/expose-api/**,/api/keep-alive/**, /api/ws/**
      ignore-resources: .js, .css, .jpg, .png, .ico, .html
      ajax-failure-response:
        content-type: application/json
        code: 401
        msg: 用户未登录
    redis:
      address: redis://127.0.0.1:6379