package com.rany.cake.devops.base.infra.po;

import java.util.Date;

public class AlarmGroupNotifyPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_notify.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_notify.group_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_notify.notify_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Long notifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_notify.notify_type
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Integer notifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_notify.deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_notify.create_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_notify.update_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_notify.id
     *
     * @return the value of alarm_group_notify.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_notify.id
     *
     * @param id the value for alarm_group_notify.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_notify.group_id
     *
     * @return the value of alarm_group_notify.group_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_notify.group_id
     *
     * @param groupId the value for alarm_group_notify.group_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_notify.notify_id
     *
     * @return the value of alarm_group_notify.notify_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Long getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_notify.notify_id
     *
     * @param notifyId the value for alarm_group_notify.notify_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setNotifyId(Long notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_notify.notify_type
     *
     * @return the value of alarm_group_notify.notify_type
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Integer getNotifyType() {
        return notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_notify.notify_type
     *
     * @param notifyType the value for alarm_group_notify.notify_type
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setNotifyType(Integer notifyType) {
        this.notifyType = notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_notify.deleted
     *
     * @return the value of alarm_group_notify.deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_notify.deleted
     *
     * @param deleted the value for alarm_group_notify.deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_notify.create_time
     *
     * @return the value of alarm_group_notify.create_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_notify.create_time
     *
     * @param createTime the value for alarm_group_notify.create_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_notify.update_time
     *
     * @return the value of alarm_group_notify.update_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_notify.update_time
     *
     * @param updateTime the value for alarm_group_notify.update_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}