package com.rany.cake.devops.base.infra.po;

import java.util.Date;

public class AlarmGroupUserPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_user.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_user.group_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_user.user_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_user.username
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_user.deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_user.create_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarm_group_user.update_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_user.id
     *
     * @return the value of alarm_group_user.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_user.id
     *
     * @param id the value for alarm_group_user.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_user.group_id
     *
     * @return the value of alarm_group_user.group_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_user.group_id
     *
     * @param groupId the value for alarm_group_user.group_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_user.user_id
     *
     * @return the value of alarm_group_user.user_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_user.user_id
     *
     * @param userId the value for alarm_group_user.user_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_user.username
     *
     * @return the value of alarm_group_user.username
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_user.username
     *
     * @param username the value for alarm_group_user.username
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_user.deleted
     *
     * @return the value of alarm_group_user.deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_user.deleted
     *
     * @param deleted the value for alarm_group_user.deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_user.create_time
     *
     * @return the value of alarm_group_user.create_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_user.create_time
     *
     * @param createTime the value for alarm_group_user.create_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarm_group_user.update_time
     *
     * @return the value of alarm_group_user.update_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarm_group_user.update_time
     *
     * @param updateTime the value for alarm_group_user.update_time
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}