package com.rany.cake.devops.base.infra.po;

import java.math.BigDecimal;
import java.util.Date;

public class AppEnvPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.id
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.cluster_id
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private Long clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.app_id
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.domain
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.env_name
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private String envName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.env
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private String env;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.max_replicas
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private Integer maxReplicas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.cpu
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private BigDecimal cpu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.memory
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private BigDecimal memory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.auto_scaling
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private String autoScaling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.need_approval
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private String needApproval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.status
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.is_deleted
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.gmt_create
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_env.gmt_modified
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.id
     *
     * @return the value of app_env.id
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.id
     *
     * @param id the value for app_env.id
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.cluster_id
     *
     * @return the value of app_env.cluster_id
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public Long getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.cluster_id
     *
     * @param clusterId the value for app_env.cluster_id
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setClusterId(Long clusterId) {
        this.clusterId = clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.app_id
     *
     * @return the value of app_env.app_id
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.app_id
     *
     * @param appId the value for app_env.app_id
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.domain
     *
     * @return the value of app_env.domain
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.domain
     *
     * @param domain the value for app_env.domain
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.env_name
     *
     * @return the value of app_env.env_name
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public String getEnvName() {
        return envName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.env_name
     *
     * @param envName the value for app_env.env_name
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setEnvName(String envName) {
        this.envName = envName == null ? null : envName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.env
     *
     * @return the value of app_env.env
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public String getEnv() {
        return env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.env
     *
     * @param env the value for app_env.env
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setEnv(String env) {
        this.env = env == null ? null : env.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.max_replicas
     *
     * @return the value of app_env.max_replicas
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public Integer getMaxReplicas() {
        return maxReplicas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.max_replicas
     *
     * @param maxReplicas the value for app_env.max_replicas
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setMaxReplicas(Integer maxReplicas) {
        this.maxReplicas = maxReplicas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.cpu
     *
     * @return the value of app_env.cpu
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public BigDecimal getCpu() {
        return cpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.cpu
     *
     * @param cpu the value for app_env.cpu
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setCpu(BigDecimal cpu) {
        this.cpu = cpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.memory
     *
     * @return the value of app_env.memory
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public BigDecimal getMemory() {
        return memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.memory
     *
     * @param memory the value for app_env.memory
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setMemory(BigDecimal memory) {
        this.memory = memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.auto_scaling
     *
     * @return the value of app_env.auto_scaling
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public String getAutoScaling() {
        return autoScaling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.auto_scaling
     *
     * @param autoScaling the value for app_env.auto_scaling
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setAutoScaling(String autoScaling) {
        this.autoScaling = autoScaling == null ? null : autoScaling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.need_approval
     *
     * @return the value of app_env.need_approval
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public String getNeedApproval() {
        return needApproval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.need_approval
     *
     * @param needApproval the value for app_env.need_approval
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setNeedApproval(String needApproval) {
        this.needApproval = needApproval == null ? null : needApproval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.status
     *
     * @return the value of app_env.status
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.status
     *
     * @param status the value for app_env.status
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.is_deleted
     *
     * @return the value of app_env.is_deleted
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.is_deleted
     *
     * @param isDeleted the value for app_env.is_deleted
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.gmt_create
     *
     * @return the value of app_env.gmt_create
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.gmt_create
     *
     * @param gmtCreate the value for app_env.gmt_create
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_env.gmt_modified
     *
     * @return the value of app_env.gmt_modified
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_env.gmt_modified
     *
     * @param gmtModified the value for app_env.gmt_modified
     *
     * @mbggenerated Wed Nov 01 21:42:10 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}