package com.rany.cake.devops.base.infra.po;

import java.util.Date;

public class CommandExecPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.account_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.exec_type
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Integer execType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.host_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String hostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.exec_status
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Integer execStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.exit_code
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Integer exitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.exec_command
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String execCommand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.description
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.log_path
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String logPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.start_date
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.end_date
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.is_deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.gmt_create
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.gmt_modified
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.creator
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.modifier
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column command_exec.user_name
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.id
     *
     * @return the value of command_exec.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.id
     *
     * @param id the value for command_exec.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.account_id
     *
     * @return the value of command_exec.account_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.account_id
     *
     * @param accountId the value for command_exec.account_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.exec_type
     *
     * @return the value of command_exec.exec_type
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Integer getExecType() {
        return execType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.exec_type
     *
     * @param execType the value for command_exec.exec_type
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setExecType(Integer execType) {
        this.execType = execType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.host_id
     *
     * @return the value of command_exec.host_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.host_id
     *
     * @param hostId the value for command_exec.host_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setHostId(String hostId) {
        this.hostId = hostId == null ? null : hostId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.exec_status
     *
     * @return the value of command_exec.exec_status
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Integer getExecStatus() {
        return execStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.exec_status
     *
     * @param execStatus the value for command_exec.exec_status
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setExecStatus(Integer execStatus) {
        this.execStatus = execStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.exit_code
     *
     * @return the value of command_exec.exit_code
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Integer getExitCode() {
        return exitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.exit_code
     *
     * @param exitCode the value for command_exec.exit_code
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setExitCode(Integer exitCode) {
        this.exitCode = exitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.exec_command
     *
     * @return the value of command_exec.exec_command
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getExecCommand() {
        return execCommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.exec_command
     *
     * @param execCommand the value for command_exec.exec_command
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setExecCommand(String execCommand) {
        this.execCommand = execCommand == null ? null : execCommand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.description
     *
     * @return the value of command_exec.description
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.description
     *
     * @param description the value for command_exec.description
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.log_path
     *
     * @return the value of command_exec.log_path
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getLogPath() {
        return logPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.log_path
     *
     * @param logPath the value for command_exec.log_path
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setLogPath(String logPath) {
        this.logPath = logPath == null ? null : logPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.start_date
     *
     * @return the value of command_exec.start_date
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.start_date
     *
     * @param startDate the value for command_exec.start_date
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.end_date
     *
     * @return the value of command_exec.end_date
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.end_date
     *
     * @param endDate the value for command_exec.end_date
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.is_deleted
     *
     * @return the value of command_exec.is_deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.is_deleted
     *
     * @param isDeleted the value for command_exec.is_deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.gmt_create
     *
     * @return the value of command_exec.gmt_create
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.gmt_create
     *
     * @param gmtCreate the value for command_exec.gmt_create
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.gmt_modified
     *
     * @return the value of command_exec.gmt_modified
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.gmt_modified
     *
     * @param gmtModified the value for command_exec.gmt_modified
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.creator
     *
     * @return the value of command_exec.creator
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.creator
     *
     * @param creator the value for command_exec.creator
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.modifier
     *
     * @return the value of command_exec.modifier
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.modifier
     *
     * @param modifier the value for command_exec.modifier
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column command_exec.user_name
     *
     * @return the value of command_exec.user_name
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column command_exec.user_name
     *
     * @param userName the value for command_exec.user_name
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}