package com.rany.cake.devops.base.infra.po;

import java.util.Date;

public class ServerProxyPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_proxy.id
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_proxy.proxy_id
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    private String proxyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_proxy.proxy_host
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    private String proxyHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_proxy.proxy_port
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    private Integer proxyPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_proxy.proxy_username
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    private String proxyUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_proxy.proxy_password
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    private String proxyPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_proxy.proxy_type
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    private Integer proxyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_proxy.description
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_proxy.is_deleted
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_proxy.gmt_create
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server_proxy.gmt_modified
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_proxy.id
     *
     * @return the value of server_proxy.id
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_proxy.id
     *
     * @param id the value for server_proxy.id
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_proxy.proxy_id
     *
     * @return the value of server_proxy.proxy_id
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public String getProxyId() {
        return proxyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_proxy.proxy_id
     *
     * @param proxyId the value for server_proxy.proxy_id
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public void setProxyId(String proxyId) {
        this.proxyId = proxyId == null ? null : proxyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_proxy.proxy_host
     *
     * @return the value of server_proxy.proxy_host
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public String getProxyHost() {
        return proxyHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_proxy.proxy_host
     *
     * @param proxyHost the value for server_proxy.proxy_host
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public void setProxyHost(String proxyHost) {
        this.proxyHost = proxyHost == null ? null : proxyHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_proxy.proxy_port
     *
     * @return the value of server_proxy.proxy_port
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public Integer getProxyPort() {
        return proxyPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_proxy.proxy_port
     *
     * @param proxyPort the value for server_proxy.proxy_port
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public void setProxyPort(Integer proxyPort) {
        this.proxyPort = proxyPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_proxy.proxy_username
     *
     * @return the value of server_proxy.proxy_username
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public String getProxyUsername() {
        return proxyUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_proxy.proxy_username
     *
     * @param proxyUsername the value for server_proxy.proxy_username
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public void setProxyUsername(String proxyUsername) {
        this.proxyUsername = proxyUsername == null ? null : proxyUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_proxy.proxy_password
     *
     * @return the value of server_proxy.proxy_password
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public String getProxyPassword() {
        return proxyPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_proxy.proxy_password
     *
     * @param proxyPassword the value for server_proxy.proxy_password
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public void setProxyPassword(String proxyPassword) {
        this.proxyPassword = proxyPassword == null ? null : proxyPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_proxy.proxy_type
     *
     * @return the value of server_proxy.proxy_type
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public Integer getProxyType() {
        return proxyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_proxy.proxy_type
     *
     * @param proxyType the value for server_proxy.proxy_type
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public void setProxyType(Integer proxyType) {
        this.proxyType = proxyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_proxy.description
     *
     * @return the value of server_proxy.description
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_proxy.description
     *
     * @param description the value for server_proxy.description
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_proxy.is_deleted
     *
     * @return the value of server_proxy.is_deleted
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_proxy.is_deleted
     *
     * @param isDeleted the value for server_proxy.is_deleted
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_proxy.gmt_create
     *
     * @return the value of server_proxy.gmt_create
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_proxy.gmt_create
     *
     * @param gmtCreate the value for server_proxy.gmt_create
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server_proxy.gmt_modified
     *
     * @return the value of server_proxy.gmt_modified
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server_proxy.gmt_modified
     *
     * @param gmtModified the value for server_proxy.gmt_modified
     *
     * @mbggenerated Wed Jan 31 21:59:39 CST 2024
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}