package com.rany.cake.devops.base.infra.po;

import java.util.Date;

public class UserEventLogPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.user_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.user_name
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.event_classify
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Integer eventClassify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.event_type
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Integer eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.log_info
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String logInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.params_json
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String paramsJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.exec_result
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Integer execResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.is_deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.gmt_create
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.gmt_modified
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.creator
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_event_log.modifier
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.id
     *
     * @return the value of user_event_log.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.id
     *
     * @param id the value for user_event_log.id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.user_id
     *
     * @return the value of user_event_log.user_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.user_id
     *
     * @param userId the value for user_event_log.user_id
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.user_name
     *
     * @return the value of user_event_log.user_name
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.user_name
     *
     * @param userName the value for user_event_log.user_name
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.event_classify
     *
     * @return the value of user_event_log.event_classify
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Integer getEventClassify() {
        return eventClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.event_classify
     *
     * @param eventClassify the value for user_event_log.event_classify
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setEventClassify(Integer eventClassify) {
        this.eventClassify = eventClassify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.event_type
     *
     * @return the value of user_event_log.event_type
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Integer getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.event_type
     *
     * @param eventType the value for user_event_log.event_type
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setEventType(Integer eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.log_info
     *
     * @return the value of user_event_log.log_info
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getLogInfo() {
        return logInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.log_info
     *
     * @param logInfo the value for user_event_log.log_info
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setLogInfo(String logInfo) {
        this.logInfo = logInfo == null ? null : logInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.params_json
     *
     * @return the value of user_event_log.params_json
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getParamsJson() {
        return paramsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.params_json
     *
     * @param paramsJson the value for user_event_log.params_json
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setParamsJson(String paramsJson) {
        this.paramsJson = paramsJson == null ? null : paramsJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.exec_result
     *
     * @return the value of user_event_log.exec_result
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Integer getExecResult() {
        return execResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.exec_result
     *
     * @param execResult the value for user_event_log.exec_result
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setExecResult(Integer execResult) {
        this.execResult = execResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.is_deleted
     *
     * @return the value of user_event_log.is_deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.is_deleted
     *
     * @param isDeleted the value for user_event_log.is_deleted
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.gmt_create
     *
     * @return the value of user_event_log.gmt_create
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.gmt_create
     *
     * @param gmtCreate the value for user_event_log.gmt_create
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.gmt_modified
     *
     * @return the value of user_event_log.gmt_modified
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.gmt_modified
     *
     * @param gmtModified the value for user_event_log.gmt_modified
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.creator
     *
     * @return the value of user_event_log.creator
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.creator
     *
     * @param creator the value for user_event_log.creator
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_event_log.modifier
     *
     * @return the value of user_event_log.modifier
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_event_log.modifier
     *
     * @param modifier the value for user_event_log.modifier
     *
     * @mbggenerated Sat Apr 26 15:56:18 CST 2025
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }
}