package com.rany.cake.devops.base.dao.mapper;

import com.rany.cake.devops.base.dao.po.AppEnvPO;

public interface AppEnvPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_env
     *
     * @mbggenerated Thu Feb 02 20:26:01 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_env
     *
     * @mbggenerated Thu Feb 02 20:26:01 CST 2023
     */
    int insert(AppEnvPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_env
     *
     * @mbggenerated Thu Feb 02 20:26:01 CST 2023
     */
    int insertSelective(AppEnvPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_env
     *
     * @mbggenerated Thu Feb 02 20:26:01 CST 2023
     */
    AppEnvPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_env
     *
     * @mbggenerated Thu Feb 02 20:26:01 CST 2023
     */
    int updateByPrimaryKeySelective(AppEnvPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_env
     *
     * @mbggenerated Thu Feb 02 20:26:01 CST 2023
     */
    int updateByPrimaryKey(AppEnvPO record);
}