dubbo:
  config-center:
    address: zookeeper://zookeeper:2181
  registry:
    address: zookeeper://zookeeper:2181
    timeout: 30000
  metadata-report:
    address: zookeeper://zookeeper:2181
    timeout: 30000

spring:
  profiles:
    active: test
  redis:
    url: redis://host.docker.internal:6379