CREATE TABLE `cake_devops`.`deploy_history` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `gmt_create` DATETIME NOT NULL,
  `gmt_modified` DATETIME NOT NULL,
  `env_id` VARCHAR(64) NOT NULL,
  `app_id` VARCHAR(45) NOT NULL,
  `start_time` DATETIME NOT NULL COMMENT '开始时间',
  `end_time` DATETIME NOT NULL COMMENT '解释时间',
  `is_deleted` CHAR(4) NOT NULL,
  `deploy_status` VARCHAR(45) NOT NULL COMMENT 'Wait, Half, Pending, Finish',
  `image_path` VARCHAR(512) NULL COMMENT '镜像地址',
  `deployment_name` VARCHAR(512) NULL,
  `content` VARCHAR(2000) NULL,
  `creator` VARCHAR(45) NULL,
  `modifier` VARCHAR(45) NULL,
  `progress` VARCHAR(2000) NULL COMMENT '进度',
  PRIMARY KEY (`id`));
